# Generated by Django 3.1.7 on 2021-09-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=250)),
                ('db_ip', models.CharField(max_length=13)),
                ('db_username', models.CharField(max_length=300)),
                ('db_password', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'База для проверки',
                'verbose_name_plural': 'Базы для проверок',
                'db_table': '_database_',
            },
        ),
        migrations.CreateModel(
            name='DatabaseFieldsToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name_to_check', models.CharField(max_length=200)),
                ('where_statement', models.CharField(max_length=100)),
                ('data_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_requests_to_check', to='main.database')),
            ],
            options={
                'verbose_name': 'Запрос, который будет проверяться.',
                'verbose_name_plural': 'Запросы, которые будут проверяться.',
                'db_table': 'database_sql_requests_constructor',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Результат Запроса',
                'verbose_name_plural': 'Результаты Запросов',
                'db_table': 'sql_request_result',
            },
        ),
        migrations.CreateModel(
            name='DatabaseMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_requests', to='main.result')),
                ('sql_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sql_request_results', to='main.databasefieldstocheck')),
            ],
            options={
                'verbose_name': 'Запрос в базу данных(выполненный)',
                'verbose_name_plural': 'Запросы в базу данных(выполненные)',
                'db_table': 'sql_request',
            },
        ),
    ]
