# Generated by Django 3.1.7 on 2021-09-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210907_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_ip',
            field=models.CharField(max_length=100),
        ),
    ]
