# Generated by Django 3.1.7 on 2021-09-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210907_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseMonitoring',
        ),
    ]
