# Generated by Django 3.1.7 on 2021-09-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_databasemonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name='result',
            name='sql_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.databasefieldstocheck'),
        ),
    ]
