# Generated by Django 3.1.7 on 2021-09-10 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_database_db_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Парсер',
                'verbose_name_plural': 'Парсеры',
                'db_table': 'parser',
            },
        ),
        migrations.CreateModel(
            name='ParserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.parser')),
            ],
            options={
                'verbose_name': 'Отчет от парсера',
                'verbose_name_plural': 'Отчеты от парсеров',
                'db_table': 'parser_report',
            },
        ),
    ]
