# Generated by Django 3.1.7 on 2021-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_parser_parserreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
