# Generated by Django 3.1.7 on 2021-09-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210910_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserDbChecker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_name', models.CharField(max_length=1000)),
                ('check_interval_in_minutes', models.IntegerField()),
                ('host', models.CharField(max_length=1000)),
                ('database_name', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('db_user_name', models.CharField(max_length=100)),
                ('rmdb', models.CharField(choices=[('My_sql', 'My_sql'), ('PostgreSQL', 'PostgreSQL')], default='PostgreSQL', max_length=100)),
                ('db_port', models.IntegerField(default=5432)),
            ],
            options={
                'verbose_name': 'База данных парсера , для проверки работы парсера',
                'verbose_name_plural': 'Базы данных парсеров , для проверки работы парсеров',
                'db_table': 'parser_database',
            },
        ),
        migrations.CreateModel(
            name='TablesToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(max_length=1000)),
                ('is_empty', models.BooleanField()),
                ('parser_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables_to_check', to='main.parserdbchecker')),
            ],
            options={
                'verbose_name': 'Таблица для проверки парсера',
                'verbose_name_plural': 'Таблицы для проверки парсеров',
                'db_table': 'table_name_for_parser',
            },
        ),
        migrations.CreateModel(
            name='ParserDbCheckerResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.tablestocheck')),
            ],
            options={
                'db_table': 'parser_databases_result',
            },
        ),
    ]
