# Generated by Django 3.1.7 on 2021-09-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_parserdbchecker_parserdbcheckerresult_tablestocheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserdbchecker',
            name='parser_name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
