# Generated by Django 3.1.7 on 2021-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210913_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablestocheck',
            name='result',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
