name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: actions/checkout@v2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SECRET_KEY }}
          script: |
            docker kill $(docker ps -q)

            docker system prune -a

            docker-compose up --build --remove-orphans