name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - run: docker kill $(docker ps -q)
      - run: docker system prune -a
      - run: docker-compose up -d --build --remove-orphans