name: Publish On Docker Hub and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  #build_and_pub:
  #  runs-on: ubuntu-latest
  #  env:
  #    LOGIN: ${{secrets.DOCKER_LOGIN}}
  #    PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  #  steps:
  #    - name: Login to docker.io
  #      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_LOGIN}}
  #    - uses: actions/checkout@master
  #    - name: Build images
  #      run: docker-compose build
  #    - name: Push image to docker.io
  #      run: docker push ?


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SECRET_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git pull origin master

            docker kill $(docker ps -q)

            docker system prune -a

            docker-compose up --build --remove-orphans