name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: deploy
        uses: actions/checkout@v2
      - run: docker-compose stop
      - run: docker-compose rm -f
      - run: docker volume rm service-monitoring_static
      - run: docker-compose up -d